version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build: ./backend
    env_file: .env
    volumes:
      - runlogs:${LOG_DIR}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${API_PORT}:8080"
    restart: unless-stopped

  frontend:
    build: ./frontend
    env_file: .env
    depends_on:
      - api
    ports:
      - "${FRONTEND_PORT}:80"
    restart: unless-stopped

volumes:
  pgdata:
    name: cicd_dashboard_pgdata
  runlogs:
    name: cicd_dashboard_runlogs